package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressCustomer generated by hbm2java
 */
@Entity
@Table(name = "address_customer", catalog = "ernest")
public class AddressCustomer implements java.io.Serializable {

	private static final long serialVersionUID = -1986178747399633195L;
	private AddressCustomerId id;
	private Customer customer;
	private Address address;
	private String isPrimaryCustomerAddress;

	public AddressCustomer() {
	}

	public AddressCustomer(AddressCustomerId id, Customer customer,
			Address address) {
		this.id = id;
		this.customer = customer;
		this.address = address;
	}

	public AddressCustomer(AddressCustomerId id, Customer customer,
			Address address, String isPrimaryCustomerAddress) {
		this.id = id;
		this.customer = customer;
		this.address = address;
		this.isPrimaryCustomerAddress = isPrimaryCustomerAddress;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false, length = 10)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false, length = 10)) })
	public AddressCustomerId getId() {
		return this.id;
	}

	public void setId(AddressCustomerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false, insertable = false, updatable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false, insertable = false, updatable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "is_primary_customer_address", length = 1)
	public String getIsPrimaryCustomerAddress() {
		return this.isPrimaryCustomerAddress;
	}

	public void setIsPrimaryCustomerAddress(String isPrimaryCustomerAddress) {
		this.isPrimaryCustomerAddress = isPrimaryCustomerAddress;
	}

}
