package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressSupplierId generated by hbm2java
 */
@Embeddable
public class AddressSupplierId implements java.io.Serializable {

	private static final long serialVersionUID = -2297780496155360530L;
	private String supplierId;
	private String addressId;

	public AddressSupplierId() {
	}

	public AddressSupplierId(String supplierId, String addressId) {
		this.supplierId = supplierId;
		this.addressId = addressId;
	}

	@Column(name = "supplier_id", nullable = false, length = 10)
	public String getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "address_id", nullable = false, length = 10)
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressSupplierId))
			return false;
		AddressSupplierId castOther = (AddressSupplierId) other;

		return ((this.getSupplierId() == castOther.getSupplierId()) || (this
				.getSupplierId() != null && castOther.getSupplierId() != null && this
				.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getAddressId() == castOther.getAddressId()) || (this
						.getAddressId() != null
						&& castOther.getAddressId() != null && this
						.getAddressId().equals(castOther.getAddressId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getAddressId() == null ? 0 : this.getAddressId().hashCode());
		return result;
	}

}
