package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactSupplierId generated by hbm2java
 */
@Embeddable
public class ContactSupplierId implements java.io.Serializable {

	private static final long serialVersionUID = 2272602614413334392L;
	private String supplierId;
	private String contactId;

	public ContactSupplierId() {
	}

	public ContactSupplierId(String supplierId, String contactId) {
		this.supplierId = supplierId;
		this.contactId = contactId;
	}

	@Column(name = "supplier_id", nullable = false, length = 10)
	public String getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "contact_id", nullable = false, length = 10)
	public String getContactId() {
		return this.contactId;
	}

	public void setContactId(String contactId) {
		this.contactId = contactId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactSupplierId))
			return false;
		ContactSupplierId castOther = (ContactSupplierId) other;

		return ((this.getSupplierId() == castOther.getSupplierId()) || (this
				.getSupplierId() != null && castOther.getSupplierId() != null && this
				.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getContactId() == castOther.getContactId()) || (this
						.getContactId() != null
						&& castOther.getContactId() != null && this
						.getContactId().equals(castOther.getContactId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getContactId() == null ? 0 : this.getContactId().hashCode());
		return result;
	}

}
