package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "freightops")
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 8714390329766351201L;
	private String id;
	private String address;
	private Date dateCreated;
	private Date dateUpdated;
	private String createdBy;
	private String updatedBy;
	private Set<AddressSupplier> addressSuppliers = new HashSet<AddressSupplier>(0);
	private Set<AddressCustomer> addressCustomers = new HashSet<AddressCustomer>(0);

	public Address() {
	}

	public Address(String id) {
		this.id = id;
	}

	public Address(String id, String address, Date dateCreated,
			Date dateUpdated, String createdBy, String updatedBy,
			Set<AddressSupplier> addressSuppliers, Set<AddressCustomer> addressCustomers) {
		this.id = id;
		this.address = address;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.addressSuppliers = addressSuppliers;
		this.addressCustomers = addressCustomers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_updated", length = 19)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<AddressSupplier> getAddressSuppliers() {
		return this.addressSuppliers;
	}

	public void setAddressSuppliers(Set<AddressSupplier> addressSuppliers) {
		this.addressSuppliers = addressSuppliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<AddressCustomer> getAddressCustomers() {
		return this.addressCustomers;
	}

	public void setAddressCustomers(Set<AddressCustomer> addressCustomers) {
		this.addressCustomers = addressCustomers;
	}

}
