package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressCustomerId generated by hbm2java
 */
@Embeddable
public class AddressCustomerId implements java.io.Serializable {

	private static final long serialVersionUID = -5851325063068701754L;
	private String customerId;
	private String addressId;

	public AddressCustomerId() {
	}

	public AddressCustomerId(String customerId, String addressId) {
		this.customerId = customerId;
		this.addressId = addressId;
	}

	@Column(name = "customer_id", nullable = false, length = 10)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "address_id", nullable = false, length = 10)
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressCustomerId))
			return false;
		AddressCustomerId castOther = (AddressCustomerId) other;

		return ((this.getCustomerId() == castOther.getCustomerId()) || (this
				.getCustomerId() != null && castOther.getCustomerId() != null && this
				.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getAddressId() == castOther.getAddressId()) || (this
						.getAddressId() != null
						&& castOther.getAddressId() != null && this
						.getAddressId().equals(castOther.getAddressId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCustomerId() == null ? 0 : this.getCustomerId()
						.hashCode());
		result = 37 * result
				+ (getAddressId() == null ? 0 : this.getAddressId().hashCode());
		return result;
	}

}
