package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactSupplier generated by hbm2java
 */
@Entity
@Table(name = "contact_supplier", catalog = "freightops")
public class ContactSupplier implements java.io.Serializable {

	private static final long serialVersionUID = -833929282757977011L;
	private ContactSupplierId id;
	private Contact contact;
	private Supplier supplier;
	private String isPrimarySupplierContact;

	public ContactSupplier() {
	}

	public ContactSupplier(ContactSupplierId id, Contact contact,
			Supplier supplier) {
		this.id = id;
		this.contact = contact;
		this.supplier = supplier;
	}

	public ContactSupplier(ContactSupplierId id, Contact contact,
			Supplier supplier, String isPrimarySupplierContact) {
		this.id = id;
		this.contact = contact;
		this.supplier = supplier;
		this.isPrimarySupplierContact = isPrimarySupplierContact;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "supplierId", column = @Column(name = "supplier_id", nullable = false, length = 10)),
			@AttributeOverride(name = "contactId", column = @Column(name = "contact_id", nullable = false, length = 10)) })
	public ContactSupplierId getId() {
		return this.id;
	}

	public void setId(ContactSupplierId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id", nullable = false, insertable = false, updatable = false)
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id", nullable = false, insertable = false, updatable = false)
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "is_primary_supplier_contact", length = 1)
	public String getIsPrimarySupplierContact() {
		return this.isPrimarySupplierContact;
	}

	public void setIsPrimarySupplierContact(String isPrimarySupplierContact) {
		this.isPrimarySupplierContact = isPrimarySupplierContact;
	}

}
