package com.sr.freightops.entity;

// Generated Mar 2, 2014 8:44:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactCustomer generated by hbm2java
 */
@Entity
@Table(name = "contact_customer", catalog = "freightops")
public class ContactCustomer implements java.io.Serializable {

	private static final long serialVersionUID = 1880338428009128940L;
	private ContactCustomerId id;
	private Customer customer;
	private Contact contact;
	private String isPrimaryCustomerContact;

	public ContactCustomer() {
	}

	public ContactCustomer(ContactCustomerId id, Customer customer,
			Contact contact) {
		this.id = id;
		this.customer = customer;
		this.contact = contact;
	}

	public ContactCustomer(ContactCustomerId id, Customer customer,
			Contact contact, String isPrimaryCustomerContact) {
		this.id = id;
		this.customer = customer;
		this.contact = contact;
		this.isPrimaryCustomerContact = isPrimaryCustomerContact;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false, length = 10)),
			@AttributeOverride(name = "contactId", column = @Column(name = "contact_id", nullable = false, length = 10)) })
	public ContactCustomerId getId() {
		return this.id;
	}

	public void setId(ContactCustomerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false, insertable = false, updatable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id", nullable = false, insertable = false, updatable = false)
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "is_primary_customer_contact", length = 1)
	public String getIsPrimaryCustomerContact() {
		return this.isPrimaryCustomerContact;
	}

	public void setIsPrimaryCustomerContact(String isPrimaryCustomerContact) {
		this.isPrimaryCustomerContact = isPrimaryCustomerContact;
	}

}
